loss:
    kind: l2
    regularization:
        kind: lasso
        beta: 1.0

model:
    name: linear_regression
    bias: True

optim:
    name: sgd
    step_size: 1.0e-3 

training:
    n_epochs: 10

dataset: /path/to/dataset.csv
